***GO_STP_71: SURAJ SANJEEV PAWAR***

**Goeduhub Technologies**<br>
***https://www.goeduhub.com/***

**Assignment/Task 4**<br>
***Online Summer training on Machine Learning & Data Science With Python***

###***Q.1 Import the numpy package under the name np and Print the numpy version and the configuration.***

In [1]:
import numpy as np
print(np.__version__)

1.19.5


###***Q.2 Create a null vector of size 10.***

In [3]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


###***Q.3 Create Simple 1-D array and check type and check data types in array.***

In [8]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


###***Q.4 How to find number of dimensions, bytes per element and bytes of memory used?***

In [11]:
import numpy as np
a=np.array([[10, 20, 30], [40, 50, 60]])
print(a)
print("Dimension of the given array",a.ndim)
print("Total byte used of the given array",a.nbytes)
print("Bytes per element of the given array",a.size)

[[10 20 30]
 [40 50 60]]
Dimension of the given array 2
Total byte used of the given array 48
Bytes per element of the given array 6


###***Q.5 Create a null vector of size 10 but the fifth value which is 1.***

In [12]:
a=np.zeros(10)
print(a)
a[4]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###***Q.6 Create a vector with values ranging from 10 to 49.***

In [13]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


###***Q.7 Reverse a vector (first element becomes last).***

In [14]:
a=np.arange(10,21)
print("The Given dataset of a is showing from ascd to Desc order :",a)
print("The Given dataset of a is showing from ascd to Desc order :",a[::-1])

The Given dataset of a is showing from ascd to Desc order : [10 11 12 13 14 15 16 17 18 19 20]
The Given dataset of a is showing from ascd to Desc order : [20 19 18 17 16 15 14 13 12 11 10]


###***Q.8 Create a 3x3 matrix with values ranging from 0 to 8.***


In [15]:
import numpy as np
a=np.arange(0,9)
print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


###***Q.9 Find indices of non-zero elements from [1,2,0,0,4,0]***

In [16]:
a=np.array([[1,2,0,0,4,0]])
print(np.nonzero(a))

(array([0, 0, 0]), array([0, 1, 4]))


###***Q.10 Create a 3x3 identity matrix.***

In [18]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***OR***

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###***Q.11 Create a 3x3x3 array with random values***

In [19]:
np.random.random((3,3,3))

array([[[0.79940525, 0.48623149, 0.49090175],
        [0.94193595, 0.68934707, 0.2271694 ],
        [0.35553444, 0.61230732, 0.913627  ]],

       [[0.65945395, 0.17183414, 0.85924485],
        [0.91409341, 0.70555757, 0.53700966],
        [0.02625848, 0.46834158, 0.89074386]],

       [[0.20827006, 0.97153401, 0.83127518],
        [0.10422552, 0.43394329, 0.16516764],
        [0.85732753, 0.7246747 , 0.74209191]]])

###***Q.12 Create a 10x10 array with random values and find the minimum and maximum values***

In [20]:
a=np.random.random((10,10,10))
print(a)
print("the minimum value is :",a.min())
print("the maximum value is :",a.max())

[[[0.62228717 0.89494976 0.49687608 0.3309641  0.63762388 0.80475657
   0.48253817 0.37685787 0.81477187 0.78077563]
  [0.61213795 0.37258104 0.74107035 0.54778306 0.30322429 0.92836361
   0.16613424 0.06281891 0.55978908 0.28220319]
  [0.34875055 0.5972586  0.90224601 0.55784762 0.25565045 0.14835281
   0.93246259 0.563346   0.18154133 0.93621052]
  [0.72333465 0.01758412 0.23477562 0.77775454 0.31787626 0.32072558
   0.86445001 0.94045812 0.64707207 0.79692926]
  [0.97748072 0.18303793 0.61278112 0.30310655 0.01434209 0.99225404
   0.98501269 0.69826785 0.01222757 0.02438594]
  [0.82504642 0.09206425 0.02583538 0.77674553 0.71512205 0.69787909
   0.41683036 0.47283274 0.91411457 0.65379262]
  [0.91070958 0.9927037  0.21597639 0.6947971  0.36250206 0.0378309
   0.98776706 0.38922466 0.48766808 0.77460308]
  [0.31876818 0.95696164 0.1061888  0.93663962 0.52674034 0.6157502
   0.42986346 0.18811513 0.86344336 0.14673453]
  [0.98502473 0.3274154  0.93575763 0.02035454 0.30201933 0.520939

###***Q.13 Create a random vector of size 30 and find the mean value***

In [21]:
a=np.random.random((30))
print(a)
print("Mean is given below :",np.mean(a))

[0.46032061 0.90121988 0.61740502 0.90986827 0.20247298 0.24724164
 0.58587439 0.21011197 0.40282319 0.53135938 0.86885326 0.17514431
 0.12676269 0.1317683  0.92629613 0.13801336 0.29800708 0.90634405
 0.03482249 0.72279187 0.11045276 0.0739219  0.46317206 0.15585466
 0.04476887 0.42223363 0.74440583 0.0480273  0.1720563  0.64968219]
Mean is given below : 0.4094025455259356


###***Q.14 Create a 2d array with 1 on the border and 0 inside.***

In [22]:
a=np.ones((5,5))
a[1:4,1:4]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###***Q.15 How to add a border (filled with 0's) around an existing array?***

In [23]:
a=np.zeros((5,5))
a[1:4,1:4]=1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


###***Q.16 How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?***<br>
Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]<br>

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [25]:
a= np.array([[ 10,20,30,40,50,60,80],[70,90,101,111,122,113,144]])
print("The Accessing Element 13 given are: ",a[1,5])
print("1st Row : ",a[0])
print("3rd Column :",a[0,2])
print(a[0,1:6:2])
a[1,5] = 20
print("The Replace Element 13 is given by : ",a[1,5])

The Accessing Element 13 given are:  113
1st Row :  [10 20 30 40 50 60 80]
3rd Column : 30
[20 40 60]
The Replace Element 13 is given by :  20


###***Q.17 How to Convert a 1D array to a 2D array with 2 rows.***

In [26]:
a=np.arange(10,20)
print(a)
print(a.reshape(2,5))

[10 11 12 13 14 15 16 17 18 19]
[[10 11 12 13 14]
 [15 16 17 18 19]]


###***Q.18 Create the following pattern without hardcoding. Use only numpy functions and the below input array a.***<br>
Input:<br>
a = np.array([1,2,3])<br>
Desired Output:<br>
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [27]:
a=np.array([1,2,3])
print(a)
a=np.append(np.repeat(a,3),np.tile(a,3))
print(a)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


###***Q.19 Write a program to show how Numpy taking less memory compared to Python List?***

In [28]:
m =range(1000)
import sys
a =10
print("Size of list given as :",sys.getsizeof(a)*len(m))
a1 = np.arange(1000)
print("Size of numpy array given as :",a1.size*a1.itemsize)

Size of list given as : 28000
Size of numpy array given as : 8000


###***Q.20 Write a program to show how Numpy taking less time compared to Python List?***

In [30]:
import time
import sys
size =1000000
l1 = range(size)
l2 = range(size)
n1 = np.arange(size)
n2 = np.arange(size)
start = time.time( )
res = [(x+y) for x,y in zip(l1,l2)]
print("Time take by List is : ", (time.time()-start)*1000)
start = time.time( )
res1 = n1+n2
print("Time taken by numpy array is : ", (time.time()-start)*1000)

Time take by List is :  169.4185733795166
Time taken by numpy array is :  4.686594009399414


***Thank you Mam and Goeduhub Technologies***